### User Products Route
GET http://localhost:4000/product/get-products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MTQzMzAwMzYsImV4cCI6MTYxNDQxNjQzNiwiYXVkIjoiNjAyZmQ1OWQ1NDk5ZTUwNjUyZjcwZWUzIiwiaXNzIjoicGlja3VycGFnZS5jb20ifQ.n164kWH1J72Gds7ixC6hZbGy8Fq3RMrnBtCiMo_Uut8

###GET USER ALL products
GET http://localhost:4000/product/get-products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MTQzMzAwMzYsImV4cCI6MTYxNDQxNjQzNiwiYXVkIjoiNjAyZmQ1OWQ1NDk5ZTUwNjUyZjcwZWUzIiwiaXNzIjoicGlja3VycGFnZS5jb20ifQ.n164kWH1J72Gds7ixC6hZbGy8Fq3RMrnBtCiMo_Uut8

###GET USER SINGLE product
GET http://localhost:4000/product/get-product
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MTQzMzAwMzYsImV4cCI6MTYxNDQxNjQzNiwiYXVkIjoiNjAyZmQ1OWQ1NDk5ZTUwNjUyZjcwZWUzIiwiaXNzIjoicGlja3VycGFnZS5jb20ifQ.n164kWH1J72Gds7ixC6hZbGy8Fq3RMrnBtCiMo_Uut8

{
  "id": "6039445bbe12f404e494630f"
}

### User delete product
DELETE http://localhost:4000/product/delete-product/60300626a22dee04940c1aeb
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MTQzMzAwMzYsImV4cCI6MTYxNDQxNjQzNiwiYXVkIjoiNjAyZmQ1OWQ1NDk5ZTUwNjUyZjcwZWUzIiwiaXNzIjoicGlja3VycGFnZS5jb20ifQ.n164kWH1J72Gds7ixC6hZbGy8Fq3RMrnBtCiMo_Uut8

{
  "id": "60300626a22dee04940c1aeb"
}

### User Edit package
PUT http://localhost:4000/admin/edit-product
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MTQzMzAwMzYsImV4cCI6MTYxNDQxNjQzNiwiYXVkIjoiNjAyZmQ1OWQ1NDk5ZTUwNjUyZjcwZWUzIiwiaXNzIjoicGlja3VycGFnZS5jb20ifQ.n164kWH1J72Gds7ixC6hZbGy8Fq3RMrnBtCiMo_Uut8

{
  "id": "60316899e610fe0370525148",
  "description": "This is the description of the package"
}

